// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEa-c2Qm32Bql6R7IeZ7spSEJN4P1cPA',
    appId: '1:577587095942:web:f53b9af2db17cc9078a407',
    messagingSenderId: '577587095942',
    projectId: 'camion-21921',
    authDomain: 'camion-21921.firebaseapp.com',
    storageBucket: 'camion-21921.firebasestorage.app',
    measurementId: 'G-ENY3RFKS4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DeGePk-OALHs6-A3YnCp5jPlACavJlc',
    appId: '1:577587095942:android:09346bc915a8c82078a407',
    messagingSenderId: '577587095942',
    projectId: 'camion-21921',
    storageBucket: 'camion-21921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CBZ1RwU8bsw68eqKuhDv_HvxWqiHm8Y',
    appId: '1:577587095942:ios:4926835a0bba1a6778a407',
    messagingSenderId: '577587095942',
    projectId: 'camion-21921',
    storageBucket: 'camion-21921.firebasestorage.app',
    iosBundleId: 'com.example.camion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8CBZ1RwU8bsw68eqKuhDv_HvxWqiHm8Y',
    appId: '1:577587095942:ios:4926835a0bba1a6778a407',
    messagingSenderId: '577587095942',
    projectId: 'camion-21921',
    storageBucket: 'camion-21921.firebasestorage.app',
    iosBundleId: 'com.example.camion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKEa-c2Qm32Bql6R7IeZ7spSEJN4P1cPA',
    appId: '1:577587095942:web:12e74276cf60966378a407',
    messagingSenderId: '577587095942',
    projectId: 'camion-21921',
    authDomain: 'camion-21921.firebaseapp.com',
    storageBucket: 'camion-21921.firebasestorage.app',
    measurementId: 'G-VNV9T5NN5Z',
  );
}
