
default_platform(:android)

platform :android do
  desc "Distribute app to firebase app distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons --target-platform android-arm,android-arm64,android-x64
"
     firebase_app_distribution(
    app: "1:577587095942:android:09346bc915a8c82078a407",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    groups: "testers",
    release_notes: "This is a test for android workflow on github actions",
  )
  end
end