name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - dev

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.4"
        bundler-cache: true
        working-directory: android

    - name: Create .env file
      run: |
        echo "${{ secrets.DOTENV_FILE }}" > .env

    - name: Get dependencies
      run: flutter pub get
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android distribute
      working-directory: android